// <auto-generated />
namespace BusinessData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addVonigoWorkOrderdataPoints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addVonigoWorkOrderdataPoints));
        
        string IMigrationMetadata.Id
        {
            get { return "202306071539039_addVonigoWorkOrderdataPoints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
